# https://alacritty.org/config-alacritty.html

# https://github.com/alacritty/alacritty/wiki/Keyboard-mappings
# alacritty --print-events
# glutin event: WindowEvent { window_id: WindowId(Id(140237741461568)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 33, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
#
#     The value between the brackets of Some, which is the one to use in the key property of the mapping
#     The boolean properties in ModifiersState, which indicate which modifiers to add in the mods property of the mapping (these can be concatenated using the | character)
#
# The value for the chars property of each entry in key_bindings: can be any text string and supports unicode (\uNNNN) escapes:
#
#   # Insert the `[` character
#   - { key = "LBracket", mods = "Alt", chars = "[" }
#   # Send the Ctrl+C control using its unicode value
#   - { key = "T", mods = "Control|Shift", chars = "\u0003" }
#
# The scancode is also printed in the output of --print-events and can be used directly in the key field of a mapping:
#
#   - { key = 33, mods = "Alt", chars = "[" }

# https://donsnotes.com/tech/charsets/ascii.html

[window]
decorations = "Full"  # "Full" | "None" | "Transparent" | "Buttonless"
padding = { x = 6, y = 6 }
dynamic_padding = true

[font]
size = 12.0

# https://www.nerdfonts.com/font-downloads
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

# normal.family = "Cascadia Code"
# bold.family = "Cascadia Code"
# italic.family = "Cascadia Code"
# bold_italic.family = "Cascadia Code"


[scrolling]
history = 30000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "nu"
args = ["-l"] # Use login shell to ensure your shell's dotfiles are sourced.

# Modifier keys: Shift, Control, Alt, Super (Windows/Cmd key)
# For a full list of key names, see `alacritty-bindings(5)` or the Alacritty man page.
[keyboard]
bindings = [
	#
    # macOS Specific
	#
    { key = "C", mods = "Command", action = "Copy" },
    { key = "V", mods = "Command", action = "Paste" },
    { key = "N", mods = "Command", action = "CreateNewWindow" },

	#
    # Linux/Windows Specific
	#
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },

    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "V", mods = "Control|Shift", action = "Paste" },

    # Vi Mode (default: Ctrl+Shift+Space to toggle)
    # This allows vim-like navigation in the scrollback buffer.
    # { key = "Space", mods = "Control|Shift", action = "ToggleViMode" },
	# { key = "Space", mods = "Control", chars = "\uf8fe" },

    # Hints (Ctrl+Shift+O by default for URLs)
    # This feature allows you to click on URLs, file paths, etc.
    # To open URLs with `xdg-open` (Linux/BSD):
    { key = "O", mods = "Control|Shift", action = "Open" }, # Default
    # Search (Ctrl+Shift+F by default for forward search)

    # https://en.wikipedia.org/wiki/Private_Use_Areas
    # U+E000..U+F8FF
    # { key = ",", mods = "Control", chars = "\uE000" },
    { key = ",", mods = "Control", chars = "\uf8ff" },  ## keep in sync with terminal.lua
]

